### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by LarryIVC** [LarryIVC/portfolio#12]
In this Issue, I present my `Portfolio Deployed Version`. 🚀
I use this option because I was deployed before my `Portfolio project.`  using `GitHub Pages`
The URL for this project is https://larryivc.github.io/portfolio/
Or click [here](https://larryivc.github.io/portfolio/) :technologist:
Thank for you your observations. :star2::star2:

**Comment by Qoosim** [comment]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @LarryIVC, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
