### ISSUE TITLE
Portfolio Project Desktop Version

### ISSUE THREAD

**Issue by oovillagran** [LarryIVC/portfolio#16]
It's a great project 👌. There is nothing else to say, that you followed the figma template design. 

Here are some optional comments that you can implement on your project to see it more professional:

- [ ] Please be sure that your project is completely responsive according to RWD guidelines. Try to see your project in different screen sizes, there are some things that you can change to become your project 100% responsive.
- [ ] Please check the units in your styles.scc file, try to use responsive units such as rem, em, and %.

We hope these comments can help you to improve your code.

**Comment by DamianDib9** [comment]
Really good looking project Larry! 

As Oscar suggested you should ony worry about that and you'll get a jaw dropping project.
