### ISSUE TITLE
Portfolio Project Desktop Version

### ISSUE THREAD

**Issue by Khaled-Alaa-1** [LarryIVC/portfolio#17]
It's a great project.

Here are some optional comments that you can implement on your project to see it more professional:

- [ ] Please check the units in your styles.CSS file, use responsive units such as rem, em, and %.
- [ ] suggest putting a label before the input and the text area.

**Comment by cancelei** [comment]
Another suggestion for the HTML contact form section is to add an aria-label property with text that describes the input fields.

Good job with the code, really nice work!
