### ISSUE TITLE
Morning Session Reviews

### ISSUE THREAD

**Issue by naanmohammed** [LarryIVC/portfolio#9]
A well-articulated and easily readable code. It deserves applause. However, the following optional fixes could help with improving the responsiveness of the site.

1. The use of max-width and min-width instead of width property.
2. The use of rems instead of pixels.

Well done @LarryIVC

**Comment by emarkees** [comment]
Well developed code!!!
I really have nothing to say, but for your line **[74]** and **[others]** you could use list instead div.

Happy Coding 🥂

**Comment by LarryIVC** [comment]
**@emarkees and @naanmohammed** 
Thank you very much for your comments and contributions, 😄  I will try to implement them in my code. 👍 
Happy coding 🥳

**Comment by LarryIVC** [comment]
I make the changes, thanks, friends. 🥳
